spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_site_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 923R5psv83DS
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081